[package]
name = "rdate"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
debug-assertions = false
overflow-checks = false
